export const RANDOMIZERS = {
	heritage: [
		"Akorosi",
		"Akorosi",
		"Akorosi",
		"Akorosi",
		"Akorosi",
		"Akorosi",
		"Dagger Islander",
		"Iruvian",
		"Severosi",
		"Skovlander",
		"Skovlander",
		"Tycherosi"
	],
	gender: [
		"Male",
		"Male",
		"Male",
		"Female",
		"Female",
		"Ambiguous/Unknown"
	],
	appearance: [
		"Athletic",
		"Beard",
		"Bony",
		"Chiseled",
		"Crippled / Prosthetic",
		"Cute",
		"Dark",
		"Delicate",
		"Disfigured / Maimed",
		"Elegant",
		"Fair",
		"Glasses / Monocle",
		"Handsome",
		"Large",
		"Long Hair",
		"Lovely",
		"Old",
		"Plain",
		"Plump",
		"Rough",
		"Scarred",
		"Sexy",
		"Shaved Bald",
		"Short",
		"Slim",
		"Stooped",
		"Stout",
		"Strange",
		"Striking",
		"Stylish",
		"Tall",
		"Tattooed",
		"Weathered",
		"Wig",
		"Wild",
		"Wiry",
		"Worn",
		"Young"
	],
	goal: [
		"Achievement",
		"Authority",
		"Change",
		"Chaos / Destruction",
		"Control",
		"Cooperation",
		"Freedom",
		"Happiness",
		"Infamy / Fear",
		"Justice",
		"Knowledge",
		"Love",
		"Pleasure",
		"Power",
		"Prestige / Fame",
		"Respect",
		"Revenge",
		"Wealth"
	],
	method: [
		"Alchemy",
		"Arcane",
		"Blackmail",
		"Chaos",
		"Commerce",
		"Espionage",
		"Hard Work",
		"Law / Politics",
		"Manipulation",
		"Negotiation",
		"Sabotage",
		"Strategy",
		"Study",
		"Subterfuge",
		"Teamwork",
		"Theft",
		"Threats",
		"Violence"
	],
	profession: [
		"Advocate",
		"Apiarist",
		"Architect",
		"Artist",
		"Author",
		"Bailiff",
		"Baker",
		"Baker",
		"Baker",
		"Banker",
		"Barber",
		"Barber",
		"Barber",
		"Blacksmith",
		"Blacksmith",
		"Blacksmith",
		"Bounty Hunter",
		"Brewer",
		"Brewer",
		"Brewer",
		"Butcher",
		"Butcher",
		"Butcher",
		"Captain",
		"Carpenter",
		"Carpenter",
		"Carpenter",
		"Cartwright",
		"Cartwright",
		"Cartwright",
		"Chandler",
		"Chandler",
		"Chandler",
		"Clerk",
		"Clerk",
		"Clerk",
		"Clockmaker",
		"Cobbler",
		"Cobbler",
		"Cobbler",
		"Composer",
		"Cooper",
		"Cooper",
		"Cooper",
		"Courtesan",
		"Criminal",
		"Criminal",
		"Criminal",
		"Cultivator",
		"Cultivator",
		"Cultivator",
		"Diplomat",
		"Driver",
		"Driver",
		"Driver",
		"Dyer",
		"Dyer",
		"Dyer",
		"Embroiderer",
		"Embroiderer",
		"Embroiderer",
		"Explorer",
		"Fishmonger",
		"Fishmonger",
		"Fishmonger",
		"Furrier",
		"Glass Blower",
		"Goat Herd",
		"Goat Herd",
		"Goat Herd",
		"Gondolier",
		"Gondolier",
		"Gondolier",
		"Guard",
		"Guard",
		"Guard",
		"Jailer",
		"Jeweler",
		"Journalist",
		"Leatherworker",
		"Leatherworker",
		"Leatherworker",
		"Leech",
		"Locksmith",
		"Magistrate",
		"Mason",
		"Mason",
		"Mason",
		"Merchant",
		"Merchant",
		"Merchant",
		"Messenger",
		"Messenger",
		"Messenger",
		"Musician",
		"Physicker",
		"Plumber",
		"Printer",
		"Rail Jack",
		"Roofer",
		"Roofer",
		"Roofer",
		"Ropemaker",
		"Ropemaker",
		"Ropemaker",
		"Rug Maker",
		"Rug Maker",
		"Rug Maker",
		"Sailor",
		"Sailor",
		"Sailor",
		"Scholar",
		"Scribe",
		"Servant",
		"Servant",
		"Servant",
		"Shipwright",
		"Shipwright",
		"Shipwright",
		"Soldier",
		"Sparkwright",
		"Spirit Warden",
		"Steward",
		"Tailor",
		"Tailor",
		"Tailor",
		"Tanner",
		"Tanner",
		"Tanner",
		"Tax Collector",
		"Tinkerer",
		"Tinkerer",
		"Tinkerer",
		"Treasurer",
		"Vendor",
		"Vendor",
		"Vendor",
		"Weaver",
		"Weaver",
		"Weaver",
		"Whisper",
		"Woodworker",
		"Woodworker",
		"Woodworker"
	],
	trait: [
		"Arcane",
		"Arrogant",
		"Artistic",
		"Bold",
		"Brash",
		"Brave",
		"Calculating",
		"Calm",
		"Candid",
		"Careless",
		"Cautious",
		"Cavalier",
		"Charming",
		"Cold",
		"Commanding",
		"Compassionate",
		"Confident",
		"Connected",
		"Cooperative",
		"Creative",
		"Cruel",
		"Cultured",
		"Daring",
		"Defiant",
		"Dishonest",
		"Dramatic",
		"Elitist",
		"Enigmatic",
		"Enthusiastic",
		"Erudite",
		"Experienced",
		"Fierce",
		"Flexible",
		"Friendly",
		"Gracious",
		"Greedy",
		"Haunted",
		"Insightful",
		"Kind",
		"Melancholy",
		"Moody",
		"Obsessive",
		"Paranoid",
		"Patient",
		"Popular",
		"Principled",
		"Proud",
		"Quiet",
		"Reckless",
		"Respected",
		"Ruthless",
		"Sadistic",
		"Savage",
		"Secretive",
		"Shrewd",
		"Sincere",
		"Sneaky",
		"Sophisticated",
		"Strange",
		"Stylish",
		"Subtle",
		"Suspicious",
		"Tough",
		"Vain",
		"Vengeful",
		"Vicious",
		"Visionary",
		"Volatile",
		"Weird",
		"Wise"
	],
	interests: [
		"Alchemy, medicine",
		"Antiques, artifacts, curios",
		"Arcane books, rituals",
		"Architecture, furnishings",
		"Church of Ecstasy",
		"Cooking, gardening",
		"Craft (leatherwork, etc.)",
		"Demon lore, legends",
		"Drugs, essences, tobacco",
		"Essences, alchemy",
		"Exploration, adventure",
		"Fine arts, opera, theater",
		"Fine clothes, jewelry, furs",
		"Fine food, restaurants",
		"Fine whiskey, wine, beer",
		"Forgotten gods",
		"Gadgets, new technology",
		"Gambling, cards, dice",
		"History, legends",
		"Horses, riding",
		"Hunting, shooting",
		"Lovers, romance, trysts",
		"Music, instruments, dance",
		"Natural philosophy",
		"Painting, drawing, sculpture",
		"Parties, social events",
		"Path of Echoes",
		"Pets (birds, dogs, cats)",
		"Pit-fighting, duels",
		"Poetry, novels, writing",
		"Politics, journalism",
		"Pre-cataclysm legends",
		"Ships, boating",
		"Spectrology, electroplasm",
		"Weapons collector",
		"Weeping Lady, charity"
	],
	quirk: [
		"A fraud. Some important aspect is fabricated.",
		"Bigoted against culture / belief / social class.",
		"Black sheep / outcast from family or organization.",
		"Blind to flaws in friends, allies, family, etc.",
		"Celebrity. Popularized in print / song / theater.",
		"Concerned with appearances, gossip, peers.",
		"Cursed, haunted, harassed by spirits or demon.",
		"Deeply traditional. Opposed to new ideas.",
		"Devoted to their family.",
		"Drug / alcohol abuser. Often impaired by their vice.",
		"Extensive education on every scholarly subject.",
		"Has chronic illness that requires frequent care.",
		"Holds their position due to blackmail.",
		"Holds their position to spy for another faction.",
		"In prison or under noble’s house arrest.",
		"Inherited their position. May not deserve / want it.",
		"Intense, unreasonable phobia or loathing.",
		"Involved with war crimes from the Unity War.",
		"Is blindly faithful to an ideal, group, or tradition.",
		"Keeps detailed journals, notes, records, ledgers.",
		"Leads a double life using cover identity.",
		"Married into important / powerful family.",
		"Massive debts (to banks / criminals / family)",
		"Once hollowed, then restored. Immune to spirits.",
		"Proud of heritage, traditions, native language.",
		"Reclusive. Prefers to interact via messengers.",
		"Relies on council to make decisions.",
		"Revolutionary. Plots against the Imperium.",
		"Scandalous reputation (deserved or not).",
		"Secretly (openly?) controlled by possessing spirit.",
		"Serves a demon’s agenda (knowingly or not).",
		"Spotless reputation. Highly regarded.",
		"Superstitious. Believes in signs, magic numbers.",
		"Surrounded by sycophants, supplicants, toadies.",
		"Visionary. Holds radical views for future.",
		"Well-traveled. Connections outside Doskvol."
	],
	style: {
		male: [
			"Apron",
			"Cane",
			"Collared Shirt",
			"Crutches",
			"Eelskin Bodysuit",
			"Face Mask",
			"Fitted Leggings",
			"Heavy Cloak",
			"Heavy Gloves",
			"Hide & Furs",
			"Hood & Veil",
			"Hooded Coat",
			"Knit Cap",
			"Leathers",
			"Long Coat",
			"Long Scarf",
			"Loose Silks",
			"Mask & Robes",
			"Rough Tunic",
			"Sharp Trousers",
			"Short Cloak",
			"Slim Jacket",
			"Soft Boots",
			"Suit & Vest",
			"Suspenders",
			"Tall Boots",
			"Tatters",
			"Thick Greatcoat",
			"Tool Belt",
			"Tricorn Hat",
			"Uniform",
			"Waxed Coat",
			"Wheelchair",
			"Wide Belt",
			"Work Boots"
		],
		female: [
			"Apron",
			"Cane",
			"Crutches",
			"Eelskin Bodysuit",
			"Face Mask",
			"Fitted Dress",
			"Fitted Leggings",
			"Heavy Cloak",
			"Heavy Gloves",
			"Hide & Furs",
			"Hood & Veil",
			"Hooded Coat",
			"Knit Cap",
			"Leathers",
			"Long Coat",
			"Long Scarf",
			"Loose Silks",
			"Mask & Robes",
			"Rough Tunic",
			"Sharp Trousers",
			"Short Cloak",
			"Skirt & Blouse",
			"Slim Jacket",
			"Soft Boots",
			"Suspenders",
			"Tall Boots",
			"Tatters",
			"Thick Greatcoat",
			"Tool Belt",
			"Uniform",
			"Waxed Coat",
			"Wheelchair",
			"Wide Belt",
			"Work Boots"
		]
	},
	name_title: [
		"Adept",
		"Archivist",
		"Captain",
		"Charter",
		"Scrivener"
	],
	name_first: {
		male: [
			"Abel",
			"Abenthy",
			"Adric",
			"Airic",
			"Alabaster",
			"Alastair",
			"Aldo",
			"Alen",
			"Aleph",
			"Ambrose",
			"Amosen",
			"Andal",
			"Andrel",
			"Anton",
			"Aquilla",
			"Aradan",
			"Aram",
			"Archibald",
			"Archie",
			"Arden",
			"Arliden",
			"Arlyn",
			"Armand",
			"Arquo",
			"Arrell",
			"Arvus",
			"Asher",
			"Aurelio",
			"Benedict",
			"Bolster",
			"Brace",
			"Bran",
			"Brance",
			"Branon",
			"Bricks",
			"Brock",
			"Brutus",
			"Caius",
			"Carro",
			"Casian",
			"Cato",
			"Cavelle",
			"Cedric",
			"Chance",
			"Chauncey",
			"Cid",
			"Clave",
			"Cliff",
			"Cornelius",
			"Cross",
			"Crowl",
			"Cym",
			"Cyrus",
			"Declan",
			"Del",
			"Drav",
			"Drazhan",
			"Drem",
			"Edlun",
			"Edmund",
			"Edrom",
			"Edwin",
			"Elan",
			"Elend",
			"Elias",
			"Elodin",
			"Ephrim",
			"Erasmus",
			"Eremon",
			"Ethan",
			"Everitt",
			"Feldspar",
			"Fero",
			"Finn",
			"Fisher",
			"Galen",
			"Gallahad",
			"Garner",
			"Gilbert",
			"Glint",
			"Gnik",
			"Gregalos",
			"Grey",
			"Greyson",
			"Grifter",
			"Grine",
			"Gristofer",
			"Hadrian",
			"Hagran",
			"Hammond",
			"Hix",
			"Holtz",
			"Hugo",
			"Iden",
			"Irton",
			"Isaac",
			"Ivellios",
			"Jabari",
			"Jericho",
			"Jerod",
			"Kazimir",
			"Kellan",
			"Kelvyn",
			"Kelyr",
			"Khafra",
			"Kobb",
			"Kristov",
			"Kyrilu",
			"Lael",
			"Lafayette",
			"Laudius",
			"Lawrence",
			"Leif",
			"Lem",
			"Lenny",
			"Logan",
			"Lucas",
			"Lucius",
			"Lysander",
			"Milos",
			"Mord",
			"Morketh",
			"Morlan",
			"Myre",
			"Narcus",
			"Nehi",
			"Noggs",
			"Norton",
			"Obel",
			"Obelas",
			"Octavius",
			"Odelay",
			"Orem",
			"Orlan",
			"Orth",
			"Orton",
			"Pavel",
			"Perceval",
			"Percival",
			"Peregrine",
			"Phin",
			"Phineas",
			"Porto",
			"Preston",
			"Primo",
			"Quess",
			"Quill",
			"Rafe",
			"Rasmus",
			"Raul",
			"Resh",
			"Rias",
			"Ring",
			"Rivallo",
			"Rodmund",
			"Roethe",
			"Roose",
			"Roric",
			"Sethla",
			"Silas",
			"Sindri",
			"Snitch",
			"Sol",
			"Solomon",
			"Sprig",
			"Stavrul",
			"Stellan",
			"Stev",
			"Sym",
			"Tacitus",
			"Tarn",
			"Taylor",
			"Thackeray",
			"Thaddeus",
			"Thane",
			"Thelian",
			"Theo",
			"Theron",
			"Thurston",
			"Timoth",
			"Tisk",
			"Tocker",
			"Tristero",
			"Ulric",
			"Vask",
			"Veleris",
			"Ventaro",
			"Virgil",
			"Vond",
			"Wax",
			"Wayne",
			"Weaver",
			"Wester",
			"Winsley"
		],
		female: [
			"Adaire",
			"Adelaide",
			"Adella",
			"Adroit",
			"Ailen",
			"Aina",
			"Akilah",
			"Albinia",
			"Althaea",
			"Alyosha",
			"Ansa",
			"Arabella",
			"Arwyl",
			"Ashlyn",
			"Avora",
			"Brena",
			"Brenna",
			"Calienthe",
			"Camilla",
			"Candor",
			"Candra",
			"Carissa",
			"Cascabel",
			"Casslyn",
			"Castille",
			"Celeste",
			"Chen",
			"Claret",
			"Clementine",
			"Constance",
			"Cordelia",
			"Corille",
			"Corsica",
			"Cyrene",
			"Dahlia",
			"Daphnia",
			"Delia",
			"Dena",
			"Denna",
			"Desmona",
			"Dolores",
			"Drenna",
			"Edie",
			"Eira",
			"Elsie",
			"Emeline",
			"Etta",
			"Fela",
			"Felicity",
			"Galenica",
			"Galina",
			"Gitta",
			"Gloria",
			"Gwen",
			"Hedy",
			"Hella",
			"Helles",
			"Henrietta",
			"Iduna",
			"Iona",
			"Isa",
			"Isabella",
			"Iskra",
			"Isolde",
			"Jasna",
			"Jaxi",
			"Joan",
			"Juno",
			"Kamelin",
			"Kari",
			"Koli",
			"Lauria",
			"Lenia",
			"Leona",
			"Leyva",
			"Lieu",
			"Lilith",
			"Lin",
			"Lizete",
			"Lorette",
			"Lucella",
			"Lynthia",
			"Lyra",
			"Maia",
			"Maiathah",
			"Maie",
			"Mara",
			"Marasi",
			"Marielda",
			"Marisol",
			"Marris",
			"Mira",
			"Naria",
			"Nasha",
			"Octavia",
			"Odrienne",
			"Olivia",
			"Ora",
			"Ordenna",
			"Oressia",
			"Orsella",
			"Pardenna",
			"Penelope",
			"Penny",
			"Phoebe",
			"Polonia",
			"Pravda",
			"Prudence",
			"Quelenna",
			"Raisa",
			"Redji",
			"Remira",
			"Rey",
			"Riven",
			"Runa",
			"Sabina",
			"Sabinia",
			"Sabrina",
			"Sadeh",
			"Sahar",
			"Selma",
			"Sesereth",
			"Severea",
			"Silaqui",
			"Skannon",
			"Sprig",
			"Stabitha",
			"Syra",
			"Tabitha",
			"Talitha",
			"Tamsyn",
			"Tasi",
			"Terra",
			"Tesslyn",
			"Thava",
			"Thena",
			"Tiff",
			"Una",
			"Vaurin",
			"Veretta",
			"Vesna",
			"Vestine",
			"Vey",
			"Victoria",
			"Vin",
			"Vita",
			"Volette",
			"Vorka",
			"Wander",
			"Ylva",
			"Zahra",
			"Zaida",
			"Zamira",
			"Zarya"
		]
	},
	name_surname: [
		"Abberwick",
		"Adelbury",
		"Adleton",
		"Aloro",
		"Alsa",
		"Ankhayat",
		"Arran",
		"Ashton",
		"Ashweather",
		"Athanoch",
		"Axelrod",
		"Backworth",
		"Barrow",
		"Basran",
		"Black",
		"Blackford",
		"Blackpool",
		"Blackthorne",
		"Bluff",
		"Boden",
		"Booker",
		"Boulder",
		"Bowman",
		"Braeside",
		"Bramble",
		"Braum",
		"Bray",
		"Breakiron",
		"Bristle",
		"Brocken",
		"Brogan",
		"Bromley",
		"Burnsides",
		"Caebrek",
		"Cartwright",
		"Carver",
		"Childermass",
		"Claw",
		"Clelland",
		"Clemont",
		"Clermont",
		"Cobblecarver",
		"Coleburn",
		"Combe",
		"Comber",
		"Crofty",
		"Cunningham",
		"Daava",
		"Dal",
		"Dalmore",
		"Danfield",
		"Drawlight",
		"Drigg",
		"Dunvil",
		"Elmore",
		"Eveningeyes",
		"Evensteps",
		"Eventide",
		"Everpenny",
		"Fairplay",
		"Farros",
		"Fellwater",
		"Fogg",
		"Gatcombe",
		"Glasseye",
		"Goldsworth",
		"Grave",
		"Graythwaite",
		"Greysteel",
		"Grine",
		"Haig",
		"Half-Off",
		"Havelton",
		"Havenhorst",
		"Hectares",
		"Helker",
		"Helles",
		"Hellyers",
		"Hemme",
		"Hightower",
		"Hightown",
		"Highwater",
		"Hill",
		"Hitchcock",
		"Innerwick",
		"Jayan",
		"Jeduin",
		"Kardera",
		"Karstas",
		"Keel",
		"Kempt",
		"Kessarin",
		"Kinclaith",
		"King",
		"Lake",
		"Larriston",
		"Leake",
		"Lomond",
		"Longstaff",
		"Lorewood",
		"Maroden",
		"Mayson",
		"Merriweather",
		"Michter",
		"Mindwell",
		"Morcombe",
		"Morriston",
		"Mortimer",
		"Netherton",
		"Night",
		"Nighteyre",
		"Nightly",
		"Noctoft",
		"Notherhome",
		"Orchard",
		"Orchid",
		"Path",
		"Peak",
		"Pegg",
		"Penderyn",
		"Pond",
		"Pool",
		"Prichard",
		"Raines",
		"Ravenglass",
		"Ravenwood",
		"Reigns",
		"Reyes",
		"Reynes",
		"Rhodes",
		"Riverford",
		"Robel",
		"Rowan",
		"Sable",
		"Sage",
		"Salkara",
		"Salos",
		"Sevoy",
		"Shilbottle",
		"Shillmoor",
		"Shook",
		"Skelkallan",
		"Skora",
		"Slane",
		"Song",
		"Steadystep",
		"Stoutale",
		"Stovestoker",
		"Strange",
		"Strangford",
		"Strathmill",
		"Sunder",
		"Sunderland",
		"Swiftwhistle",
		"Tailor",
		"Tallfellow",
		"Templeton",
		"Tenpenny",
		"Tevilton",
		"Thistle",
		"Thrysus",
		"Thurston",
		"Tinmouth",
		"Tower",
		"Tristé",
		"Tyrconnell",
		"Vale",
		"Valentine",
		"Veldaire",
		"Venture",
		"Walund",
		"Warren",
		"Waters",
		"Wecker",
		"Welker",
		"Wend",
		"Wharver",
		"Whythe",
		"Woodall"
	],
	name_alias: [
		"Bell",
		"Birch",
		"Bird",
		"Bliss",
		"Bricks",
		"Bug",
		"Chime",
		"Coil",
		"Cricket",
		"Cross",
		"Crow",
		"Echo",
		"Flint",
		"Frog",
		"Frost",
		"Goods",
		"Grip",
		"Gunner",
		"Hammer",
		"Hook",
		"Ink",
		"Junker",
		"Mist",
		"Moon",
		"Nail",
		"Needle",
		"Ogre",
		"Pool",
		"Ring",
		"Ruby",
		"Silver",
		"Skinner",
		"Song",
		"Spur",
		"Tackle",
		"Thistle",
		"Thorn",
		"Tick",
		"Tick-Tock",
		"Tock",
		"Trick",
		"Twelves",
		"Vixen",
		"Whip",
		"Wicker"
	],
	name_suffix: [
		"Jr.",
		"Sr.",
		"III",
		"IV"
	]
};